### PR TITLE
Add sandbox mode to CI testing matrix

### PR DESCRIPTION
**Pull request by gyfelton**
What changed:
1. Add sandbox on/off to testing matrix, so we have 2 bazel version * VFS on/off * sandbox on off = 8 tests in total ATM
2. Fix redefinition of `AppErrorCode` enum error in sandbox mode by removing the extra import in bridging header. The tests still works and can catch renaming of the enum for example. Why it was working in non sandbox mode is unknown
3. Add `sandbox` config to include all settings needed to pass CI. specifically allow a small set of actions to run locally.

Why this change:
To add CI coverage to sandbox mode to ensure no regression on it, now that we have fixed issues with sandbox mode in https://github.com/bazel-ios/rules_ios/pull/894

Discussion:
CI duration might be a concern, we can exclude certain combo in the test matrix if we want, it's possible with `exclude` keyword

### CODE REVIEW

File: .bazelrc [hunk 1]
```diff
@@ -62,6 +62,14 @@ build:remote_cache --noslim_profile
 build:remote_cache --remote_cache=grpcs://remote.buildbuddy.io
 build:remote_cache --remote_timeout=3600
 
+build:sandboxed --strategy=SwiftCompile=sandboxed
```
Comment (luispadron) [inline .bazelrc:65]: Is it possible to test sandboxed for all actions here and only allow certain ones to fallback to local instead? This might give us more info

Comment (gyfelton) [reply .bazelrc:65]: that's what we are doing here no? default setting has swiftCompile using worker and everything else local
This new config is everything sandboxed with a select set being allowed to fallback to local

File: .bazelrc [hunk 2]
```diff
@@ -62,6 +62,14 @@ build:remote_cache --noslim_profile
...
+build:sandboxed --spawn_strategy=sandboxed
+build:sandboxed --strategy=Genrule=sandboxed,local
+build:sandboxed --strategy=StoryboardCompile=sandboxed,local
+build:sandboxed --strategy=CleaningFramework=sandboxed,local
+build:sandboxed --strategy=StoryboardLink=sandboxed,local
+build:sandboxed --strategy=ProcessAndSign=sandboxed,local
```
[the remark this answers is not in the document]
Comment (gyfelton) [reply .bazelrc:71]: without them CI fails with `No usable spawn strategy found for spawn with mnemonic XXX. Are your --spawn_strategy or --strategy flags too strict?` error.
This list might grow in future, but I don't think they need to be run in sandbox anyway.

File: .bazelrc (hunk 1 above)
Comment (luispadron) [reply .bazelrc:65]: I meant, could we do `--strategy=sandboxed`

File: .bazelrc (hunk 2 above)
[the remark this answers is not in the document]
Comment (luispadron) [reply .bazelrc:71]: Gotcha, that makes sense

File: .bazelrc (hunk 1 above)
Comment (luispadron) [reply .bazelrc:65]: hmm i guess you need it to override the above like:

```
build --strategy=SwiftCompile=worker
```

nvm this all looks good, thank you!

**Comment by luispadron** [comment]
Updated the required check in GitHub this should be ready once CI completes

**Review by thiagohmcruz — APPROVED** [review]
